apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: uts-devops:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000


