apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: projek-uts-devops:latest
          imagePullPolicy: Never
          ports:
<<<<<<< HEAD
            - containerPort: 3000
=======
            - containerPort: 3000
>>>>>>> f149560348c91028d9465368363fd39acd2d1731
